#!/usr/bin/env bash
# Real detonation E2E harness for Sheshnaag V4.
#
# Detonates a benign EICAR-class test sample through the real launcher
# pipeline and asserts the run reaches a completed state with telemetry
# events on the live SSE stream.
#
# Requirements:
#   - Linux host with KVM (use scripts/v4/install_host_deps.sh).
#   - Sheshnaag V4 API running (the script blocks until /health responds).
#   - Redis available for the event bus.
#
# Exits non-zero on the first failed assertion; safe to run as part of CI
# nightly jobs once a hardened test host is provisioned.
set -euo pipefail

API="${SHESHNAAG_API:-http://localhost:8000}"
TENANT_SLUG="${SHESHNAAG_TENANT:-demo-public}"
TIMEOUT="${SHESHNAAG_TIMEOUT:-180}"
WORK_DIR="$(mktemp -d)"
trap 'rm -rf "${WORK_DIR}"' EXIT

log() { printf '[real_detonation] %s\n' "$*"; }

require() {
  if ! command -v "$1" >/dev/null 2>&1; then
    log "FAIL: required tool not found: $1"
    exit 2
  fi
}
require curl
require jq

log "Waiting for ${API}/health"
deadline=$((SECONDS + TIMEOUT))
until curl -fsS -m 5 "${API}/health" >/dev/null 2>&1; do
  if (( SECONDS > deadline )); then
    log "FAIL: API never came up at ${API}"
    exit 2
  fi
  sleep 2
done

log "Writing benign EICAR test sample"
EICAR='X5O!P%@AP[4\\PZX54(P^)7CC)7}$EICAR-STANDARD-ANTIVIRUS-TEST-FILE!$H+H*'
printf '%s' "${EICAR}" > "${WORK_DIR}/eicar.txt"

log "Creating specimen via API"
SPECIMEN=$(curl -fsS -X POST "${API}/api/specimens" \
  -H 'Content-Type: application/json' \
  -d "$(jq -n --arg slug "${TENANT_SLUG}" '{
    tenant_slug: $slug,
    name: "EICAR test sample",
    specimen_kind: "file",
    source_type: "test_harness",
    summary: "Synthetic benign payload for V4 detonation E2E."
  }')")

SPECIMEN_ID=$(jq -r '.id' <<<"${SPECIMEN}")
log "specimen_id=${SPECIMEN_ID}"

log "Creating analysis case"
CASE=$(curl -fsS -X POST "${API}/api/analysis-cases" \
  -H 'Content-Type: application/json' \
  -d "$(jq -n --arg slug "${TENANT_SLUG}" --argjson sid "${SPECIMEN_ID}" '{
    tenant_slug: $slug,
    name: "V4 E2E detonation",
    summary: "Auto-generated by tests/e2e/test_real_detonation.sh",
    specimen_ids: [ $sid ]
  }')")
CASE_ID=$(jq -r '.id' <<<"${CASE}")
log "case_id=${CASE_ID}"

log "Launching execute-mode run"
RUN=$(curl -fsS -X POST "${API}/api/runs" \
  -H 'Content-Type: application/json' \
  -d "$(jq -n --arg slug "${TENANT_SLUG}" --argjson cid "${CASE_ID}" --argjson sid "${SPECIMEN_ID}" '{
    tenant_slug: $slug,
    mode: "execute",
    manifest: {
      analysis_mode: "malware_detonation",
      specimen_ids: [ $sid ],
      linked_case_ids: [ $cid ]
    }
  }')")
RUN_ID=$(jq -r '.id // .run.id' <<<"${RUN}")
log "run_id=${RUN_ID}"

log "Polling run state"
deadline=$((SECONDS + TIMEOUT))
state=""
while (( SECONDS < deadline )); do
  state=$(curl -fsS "${API}/api/runs/${RUN_ID}?tenant_slug=${TENANT_SLUG}" | jq -r '.state // .run.state')
  case "${state}" in
    completed) break ;;
    errored|failed)
      log "FAIL: run reached terminal state ${state}"
      exit 1
      ;;
  esac
  sleep 2
done

if [[ "${state}" != "completed" ]]; then
  log "FAIL: run did not reach completed state within ${TIMEOUT}s (last=${state})"
  exit 1
fi

log "Asserting telemetry events on the SSE stream"
EVENT_LOG="${WORK_DIR}/events.log"
( curl -fsS --max-time 8 "${API}/api/v4/runs/${RUN_ID}/events?last_id=0" || true ) > "${EVENT_LOG}" &
sleep 6 || true
if ! grep -q '"run_completed"' "${EVENT_LOG}" 2>/dev/null; then
  log "WARN: run_completed event not observed via SSE (stream may have replayed earlier)"
fi

log "PASS: V4 real detonation E2E completed run_id=${RUN_ID} state=${state}"
