"""Database models."""

from app.models.asset import Asset, AssetVulnerability
from app.models.capability import AuditLogEntry, AuthorizationArtifact
from app.models.cve import CVE, AffectedProduct, CVEReference
from app.models.embeddings import (
    VECTOR_DIM,
    KnowledgeChunkEmbedding,
    SpecimenBehaviorEmbedding,
    VectorOrJSON,
)
from app.models.exploit import Exploit
from app.models.integrations import CaseIntegrationLink
from app.models.malware_lab import (
    AISession,
    AnalysisCase,
    BehaviorFinding,
    CaseFieldSchema,
    CaseStateTransition,
    DefangAction,
    IndicatorArtifact,
    MalwareReport,
    PreventionArtifact,
    SandboxProfile,
    ScopePolicy,
    Specimen,
    SpecimenRevision,
)
from app.models.oidc import OidcProvider
from app.models.ops import FeedSyncRun, FeedSyncState, PatchDependency, PatchPlan, PatchPlanItem
from app.models.patch import AssetPatch, Patch, patch_cves
from app.models.rbac import Permission, Role, RolePermission
from app.models.risk_score import RiskHistory, RiskScore
from app.models.sheshnaag import (
    AdvisoryPackageLink,
    AdvisoryRecord,
    AnalystIdentity,
    AttestationRecord,
    CandidateScoreRecalculationRun,
    ContributionLedgerEntry,
    DetectionArtifact,
    DisclosureBundle,
    EvidenceArtifact,
    ExploitSignal,
    KnowledgeWikiPage,
    LabRecipe,
    LabRun,
    LabTemplate,
    MaintainerAssessment,
    MitigationArtifact,
    PackageRecord,
    ProductRecord,
    RawKnowledgeSource,
    RecipeRevision,
    ResearchCandidate,
    ReviewDecision,
    RunEvent,
    SourceFeed,
    TenantSigningKey,
    VersionRange,
    WorkstationFingerprint,
)
from app.models.v2 import (
    AnalystFeedback,
    AssetSoftware,
    AttackTechnique,
    CVEAttackTechnique,
    DecisionAuditEvent,
    EPSSSnapshot,
    EvidenceItem,
    ExposureGraphEdge,
    ExposureGraphNode,
    IdentityPrincipal,
    KEVEntry,
    KnowledgeChunk,
    KnowledgeDocument,
    NetworkExposure,
    PatchApproval,
    Service,
    SimulationRun,
    SoftwareComponent,
    Tenant,
    TenantMembership,
    TenantUser,
    VexStatement,
)
from app.models.worker_pool import Worker, WorkerCaKey, WorkerEnrollmentToken

__all__ = [
    "CVE",
    "CVEReference",
    "AffectedProduct",
    "Exploit",
    "RiskScore",
    "RiskHistory",
    "Asset",
    "AssetVulnerability",
    "Patch",
    "AssetPatch",
    "patch_cves",
    "FeedSyncRun",
    "FeedSyncState",
    "PatchDependency",
    "PatchPlan",
    "PatchPlanItem",
    "Tenant",
    "Service",
    "SoftwareComponent",
    "AssetSoftware",
    "NetworkExposure",
    "IdentityPrincipal",
    "EvidenceItem",
    "KEVEntry",
    "EPSSSnapshot",
    "AttackTechnique",
    "CVEAttackTechnique",
    "KnowledgeChunk",
    "KnowledgeDocument",
    "ExposureGraphNode",
    "ExposureGraphEdge",
    "SimulationRun",
    "AnalystFeedback",
    "VexStatement",
    "TenantUser",
    "TenantMembership",
    "PatchApproval",
    "DecisionAuditEvent",
    "SourceFeed",
    "AdvisoryRecord",
    "AdvisoryPackageLink",
    "PackageRecord",
    "ProductRecord",
    "VersionRange",
    "ExploitSignal",
    "ResearchCandidate",
    "LabTemplate",
    "LabRecipe",
    "RecipeRevision",
    "LabRun",
    "RunEvent",
    "EvidenceArtifact",
    "DetectionArtifact",
    "MitigationArtifact",
    "DisclosureBundle",
    "AttestationRecord",
    "CandidateScoreRecalculationRun",
    "AnalystIdentity",
    "TenantSigningKey",
    "WorkstationFingerprint",
    "ContributionLedgerEntry",
    "ReviewDecision",
    "RawKnowledgeSource",
    "KnowledgeWikiPage",
    "MaintainerAssessment",
    "Specimen",
    "SpecimenRevision",
    "AnalysisCase",
    "CaseFieldSchema",
    "CaseStateTransition",
    "SandboxProfile",
    "BehaviorFinding",
    "IndicatorArtifact",
    "PreventionArtifact",
    "DefangAction",
    "MalwareReport",
    "ScopePolicy",
    "AISession",
    "KnowledgeChunkEmbedding",
    "SpecimenBehaviorEmbedding",
    "VectorOrJSON",
    "VECTOR_DIM",
    "AuditLogEntry",
    "AuthorizationArtifact",
    "Role",
    "Permission",
    "RolePermission",
    "Worker",
    "WorkerCaKey",
    "WorkerEnrollmentToken",
    "OidcProvider",
    "CaseIntegrationLink",
]
