"""Database models."""

from app.models.cve import CVE, CVEReference, AffectedProduct
from app.models.exploit import Exploit
from app.models.risk_score import RiskScore, RiskHistory
from app.models.asset import Asset, AssetVulnerability
from app.models.patch import Patch, AssetPatch, patch_cves
from app.models.ops import FeedSyncState, PatchDependency, PatchPlan, PatchPlanItem
from app.models.v2 import (
    AnalystFeedback,
    AssetSoftware,
    AttackTechnique,
    CVEAttackTechnique,
    DecisionAuditEvent,
    EPSSSnapshot,
    EvidenceItem,
    ExposureGraphEdge,
    ExposureGraphNode,
    IdentityPrincipal,
    KEVEntry,
    KnowledgeChunk,
    KnowledgeDocument,
    NetworkExposure,
    PatchApproval,
    Service,
    SimulationRun,
    SoftwareComponent,
    Tenant,
    TenantMembership,
    TenantUser,
    VexStatement,
)

__all__ = [
    "CVE",
    "CVEReference", 
    "AffectedProduct",
    "Exploit",
    "RiskScore",
    "RiskHistory",
    "Asset",
    "AssetVulnerability",
    "Patch",
    "AssetPatch",
    "patch_cves",
    "FeedSyncState",
    "PatchDependency",
    "PatchPlan",
    "PatchPlanItem",
    "Tenant",
    "Service",
    "SoftwareComponent",
    "AssetSoftware",
    "NetworkExposure",
    "IdentityPrincipal",
    "EvidenceItem",
    "KEVEntry",
    "EPSSSnapshot",
    "AttackTechnique",
    "CVEAttackTechnique",
    "KnowledgeChunk",
    "KnowledgeDocument",
    "ExposureGraphNode",
    "ExposureGraphEdge",
    "SimulationRun",
    "AnalystFeedback",
    "VexStatement",
    "TenantUser",
    "TenantMembership",
    "PatchApproval",
    "DecisionAuditEvent",
]
